#remote_theme: cotes2020/jekyll-theme-chirpy

title: h4fan
# theme: jekyll-theme-hacker

description: blog about web sec, bug bounty

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate




theme: jekyll-theme-minimal
