remote_theme: chesterhow/tale

title: h4fan
# theme: jekyll-theme-hacker

description: blog about web sec, bug bounty

permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate

