remote_theme: mmistakes/minimal-mistakes

title: h4fan
# theme: jekyll-theme-hacker

description: blog about web sec, bug bounty

permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
